/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fbf9f9",
        "surface-dim": "#dbdad9",
        "surface-bright": "#fbf9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#e9e8e7",
        "surface-container-highest": "#e3e2e2",
        "surface-variant": "#e3e2e2",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#44474e",
        "inverse-surface": "#303031",
        "inverse-on-surface": "#f2f0f0",
        "outline": "#74777f",
        "outline-variant": "#c4c6cf",
        "surface-tint": "#465f88",
        "primary": "#000a1e",
        "on-primary": "#ffffff",
        "primary-container": "#002147",
        "on-primary-container": "#708ab5",
        "inverse-primary": "#aec7f6",
        "secondary": "#096969",
        "on-secondary": "#ffffff",
        "secondary-container": "#a2f0ef",
        "on-secondary-container": "#166f6f",
        "tertiary": "#180500",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3d1500",
        "on-tertiary-container": "#b97958",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#aec7f6",
        "on-primary-fixed": "#001b3d",
        "on-primary-fixed-variant": "#2d476f",
        "secondary-fixed": "#a2f0ef",
        "secondary-fixed-dim": "#86d4d3",
        "on-secondary-fixed": "#002020",
        "on-secondary-fixed-variant": "#004f4f",
        "tertiary-fixed": "#ffdbcb",
        "tertiary-fixed-dim": "#ffb691",
        "on-tertiary-fixed": "#341100",
        "on-tertiary-fixed-variant": "#6c391d",
        "background": "#fbf9f9",
        "on-background": "#1b1c1c"
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1440px"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
